-- MySQL Script generated by MySQL Workbench
-- 2020年02月02日 星期日 19时18分30秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema example
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `example` ;

-- -----------------------------------------------------
-- Schema example
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `example` DEFAULT CHARACTER SET utf8mb4 ;
USE `example` ;

-- -----------------------------------------------------
-- Table `example`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `example`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id',
  `user_name` VARCHAR(45) NOT NULL COMMENT '用户名',
  `password` VARCHAR(45) NOT NULL COMMENT '密码',
  `record_status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '数据状态',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC))
ENGINE = InnoDB
COMMENT = '用户表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `example`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `example`;
INSERT INTO `example`.`user` (`id`, `user_name`, `password`, `record_status`) VALUES (1, 'admin', '202cb962ac59075b964b07152d234b70', 1);

COMMIT;

