server:
    port: 8081
    servlet:
        context-path: /springboot

spring:
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
    datasource:
        username: root
        password: 12345
        url: jdbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
        driver-class-name: com.mysql.jdbc.Driver
    resources:
        static-locations: classpath:/static/
mybatis:
    mapper-locations: classpath:mapper/*Mapper.xml
    type-aliases-package: cn.weibin.springboot.model
    configuration:
        map-underscore-to-camel-case: true
